---
- hosts: projectrock_web
  become: yes
  become_method: sudo

  gather_facts: False

  tasks:
    - name: Delete /var/www/html/index.php
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Rename /var/www/html/index-hack.php to index.php
      command: cp /var/www/html/index-hack.php /var/www/html/index.php
 
