---
- hosts: projectrock_web
  become: yes
  become_method: sudo
  
  gather_facts: False
  pre_tasks:
    - pause:
       minutes: 2
    - raw: sudo apt-get update
      register: result
    - raw: sudo apt-get -y install python-minimal
      register: ubuntu_python_result

  tasks:
    - apt_repository:
        repo: ppa:ondrej/php
        
    - name: Download Shell Script 
      get_url:
        url: https://sveenstra.s3-ap-southeast-2.amazonaws.com/rename.sh
        dest: /home/projectrock/rename.sh
    
    - name: Change Shell Script Permissions
      file: dest=/home/projectrock/rename.sh mode=a+x

    - name: Run shell script to rename server
      shell: /home/projectrock/rename.sh
      become: true
      args:
       executable: /bin/bash

    - name: Install apache httpd  
      apt:
        name: apache2
        state: present
    
    - name: Install Git
      apt: 
        name: git-core
        state: present   

    - name: Install php7.4 
      apt:
        name: php7.4
        state: present
    
    - name: Install Mod for php7.4
      apt:
        name: libapache2-mod-php7.4
        state: present
    
    - name: Install mongo for php 7.4
      apt:
        name: php7.4-mongodb
        state: present
    
    - name: Remove index.html so /var/www/html is empty
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: Git Clone
      git:
        repo: https://github.com/sndrmn/ProjectRock.git
        dest: /var/www/html
        clone: yes
    
    - name: Download ssl.sh
      get_url:
        url: https://s3-ap-southeast-2.amazonaws.com/vmware.education/ssl.sh
        dest: /home/projectrock
        checksum: md5:7ceccae82a1ce8647fe89e3db228855a

    - name: Change Shell Script Permissions
      file: dest=/home/projectrock/ssl.sh mode=a+x
    
    - name: Run a Shell Script
      shell: /home/projectrock/ssl.sh
      become: true
      args:
       executable: /bin/bash

    - name: Change /var/www/html/Mongo.php File
      replace:
          path: /var/www/html/mongo.php
          regexp: 'mongodb.vmware.education'
          replace: "{{ website }}mongodb.vmware.education"

    - name: Change /etc/apache2/sites-available/000-default.conf
      replace:
          path: /etc/apache2/sites-available/000-default.conf
          regexp: 'projectrock.vmware.education'
          replace: "{{ website }}.vmware.education"
    
    - name: Update /etc/apache2/envvars
      lineinfile:
         path: /etc/apache2/envvars
         line: export MONGOUSER=ReadUser
    
    - name: Update/etc/apache2/envvars
      lineinfile:
         path: /etc/apache2/envvars
         line: export MONGOPASS=password

    - name:  Apache2
      systemd:
         state: restarted
         daemon_reload: yes
         name: apache2

    - name: Download SaltBoot Files
      get_url:
        url: https://bootstrap.saltstack.com
        dest: /home/projectrock/install_salt.sh
    
    - name: Change Shell Script Permissions
      file: dest=/home/projectrock/install_salt.sh mode=a+x

    - name: Run shell script to install salt minion
      shell: "/home/projectrock/install_salt.sh -A projectrock-saltmaster.vmware.education"
      become: true
      args:
       executable: /bin/bash
    


    
